services:
  # Nginx service
  nginx:
    image: nginx:alpine # Correct Nginx image
    container_name: laravel_nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html # Mount your Laravel application
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # Nginx config
    depends_on:
      - php
    networks:
      - app-network

  # PHP 8.1 FPM service
  php:
    build:
      context: . # Dockerfile is in the same folder as Laravel
      dockerfile: Dockerfile # Use the Dockerfile in the same folder
    container_name: laravel_php
    volumes:
      - .:/var/www/html # Mount the whole Laravel app to /var/www/html
    networks:
      - app-network
    depends_on:
      - mysql
      - redis
      - mongo

  # MySQL service (using MySQL 5.7 for compatibility)
  mysql:
    image: alpine/mysql
    container_name: laravel_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravelpassword
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  # Redis service
  redis:
    image: redis:alpine # Use this
    container_name: laravel_redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  # MongoDB service
  mongo:
    image: mvertes/alpine-mongo # Use the latest MongoDB image
    container_name: laravel_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  # Laravel Artisan Queue / Scheduler
  artisan:
    build:
      context: . # Dockerfile is in the same folder
      dockerfile: Dockerfile # Use the Dockerfile in the same folder
    container_name: laravel_artisan
    volumes:
      - .:/var/www/html # Mount the whole Laravel app to /var/www/html
    entrypoint: php artisan serve --host=0.0.0.0 --port=9000
    networks:
      - app-network
    depends_on:
      - php
      - mysql

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  mongo_data:
